name: Build Windows app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "3.13.2"  # Set flutter version here

      - name: Build Windows app
        run: flutter build windows --release

      - name: Copy dependencies
        run: copy .\windows\sqlite3.dll .\build\windows\runner\Release\

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: aidea
          path: build/windows/runner/Release